# Configuration file for a simple test system

title = "simple"

[description]
	name = "simple"

[system]
	base_mva = 3300
	V_base = 400
	f_base = 50
	ref_bus = 1

[components]
		lines = "lines.csv"
		loads = "loads.csv"
		generators = "generators.csv"
